# Generated by Django 3.2.6 on 2024-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='subuser',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AddField(
            model_name='subuser',
            name='visaType',
            field=models.CharField(default='Tourist', max_length=100),
        ),
    ]
